### ISSUE TITLE
can 8125 2.5G

### ISSUE THREAD

**Issue by wd1300** [bb-qq/r8152#121]

**Comment by wd1300** [comment]
can this RTL8125 2.5GbE Controller use one of these drvier,my synology use intel 10400t,thank u for answer me!

**Comment by bb-qq** [comment]
This driver does not support chips with PCIe such as RTL8125, and I does not have any plans to support them.

If you have PCIe slots, I strongly recommend to use third party AQC107 based network cards such as [ASUS XG-C100C|https://amzn.to/3vDALaA]. because these are supported out of the box and more stable than Realtek.

**Comment by wd1300** [comment]
Thanks a lot!😍

在 2021-05-29 13:00:15，bb-qq ***@***.***> 写道：


This driver does not support chips with PCIe such as RTL8125, and I does not have any plans to support them.

If you have PCIe slots, I strongly recommend to use third party AQC107 based network cards such as [ASUS XG-C100C|https://amzn.to/3vDALaA]. because these are supported out of the box and more stable than Realtek.

**Comment by bb-qq** [comment]
I close this issue.
