### ISSUE TITLE
Why need spk_su.c?

### ISSUE THREAD

**Issue by riverscn** [bb-qq/r8152#137]
I read https://help.synology.com/developer-guide/privilege/privilege_config.html and have a question.

Why not write `conf/privilege` file in the repo, instead of spk_su.c during installation process?

**Comment by bb-qq** [comment]
Since DSM 7.0, root privilege is only allowed for packaged created by Synology.
https://help.synology.com/developer-guide/privilege/preface.html

To avoid this limitation, we need to modify `conf/privilege` after the timing when the Package Manager checks its value. And privilege escalation is required to modify `conf/privilege` because post-process of installation is executed as logon user of DSM.

**Comment by riverscn** [comment]
TIL!

So it seems there is no official configuration for user package which contains a hardware driver.

**Comment by bb-qq** [comment]
Yes, you are right.
