### ISSUE TITLE
DS720+ work with Wavlink 2500Mbps

### ISSUE THREAD

**Issue by ydzhus** [bb-qq/r8152#323]
### Description of the problem

**Comment by bb-qq** [comment]
>The result started with 231 megabytes per second and then gradually fell and rose 180-190-200, later it began to fall to 128 megabytes per second. Curve in the direction of fall.

This symptom suggests that the disk read speed may not be keeping up with the copy process. (Even if you are using the SSD cache, this will have no effect if it is not on the cache.)

In order to isolate the problem, I need you to post the iperf results. Also, what happens if you run iperf from those two laptops at the same time?

**Comment by ydzhus** [comment]
> > The result started with 231 megabytes per second and then gradually fell and rose 180-190-200, later it began to fall to 128 megabytes per second. Curve in the direction of fall.
> 
> This symptom suggests that the disk read speed may not be keeping up with the copy process. (Even if you are using the SSD cache, this will have no effect if it is not on the cache.)
> 
> In order to isolate the problem, I need you to post the iperf results. Also, what happens if you run iperf from those two laptops at the same time?

1. Is it better to connect two clients via a cable or is it possible via wifi 5 and 6? I have only 1 2.5 G port in my router to which the NAS is connected. Cable clients will only be able to connect to 1G ports.

2. Is there any specific iperf test command that can be run on 2 clients? To see the maximum throughput. Since different commands have different speeds, it would be possible to standardize here somehow.

3. Could all this be due to the fact that the disks can not cope?
I have two WD40EFRX-68N32N0 in SHR mirror.

**Comment by bb-qq** [comment]
> Is it better to connect two clients via a cable or is it possible via wifi 5 and 6? I have only 1 2.5 G port in my router to which the NAS is connected. Cable clients will only be able to connect to 1G ports.

Even if each port has a maximum speed of 1 Gbps, the total will be 2 Gbps, so I think it makes sense to check if this speed is kept.

Wireless connections are not particularly suitable for testing with multiple clients because of the uncertainties and interference between clients on the airwaves.

> Is there any specific iperf test command that can be run on 2 clients? To see the maximum throughput. Since different commands have different speeds, it would be possible to standardize here somehow.

You can launch multiple instances of iperf3 by specifying a different port number for `-p 5201`.

> Could all this be due to the fact that the disks can not cope?
> I have two WD40EFRX-68N32N0 in SHR mirror.

I would like to use iperf to isolate it.

> Does it make sense to disable SSD cache for separate testing with iperf ? Although I would like to use SSD cache and have a conditional speed of 2.5G.

The SSD cache should not slow down the transfer rate.
To keep ideal transfer speeds, the entire file to be copied must be cached on the SSD.

**Comment by ydzhus** [comment]
> > The result started with 231 megabytes per second and then gradually fell and rose 180-190-200, later it began to fall to 128 megabytes per second. Curve in the direction of fall.
> 
> This symptom suggests that the disk read speed may not be keeping up with the copy process. (Even if you are using the SSD cache, this will have no effect if it is not on the cache.)
> 
> In order to isolate the problem, I need you to post the iperf results. Also, what happens if you run iperf from those two laptops at the same time?

Two clients are connected by 1G cable to the router.
In total, the server showed 232.5 megabytes per second, stable.

`iperf3 -c 192.168.1.118 -p 5202 -t 60 -i 5 -P 4 -w 128k`
![зображення](https://github.com/bb-qq/r8152/assets/141327954/89e5d09e-1d1d-4538-bedd-c2e9038faa6d)
`iperf3 -c 192.168.1.118 -p 5201 -t 60 -i 5 -P 4 -w 128k`
![зображення](https://github.com/bb-qq/r8152/assets/141327954/efc87ed6-f3a6-4e5e-8903-8b87f0ef0351)

`iperf3 -c 192.168.1.118 -p 5202`
![зображення](https://github.com/bb-qq/r8152/assets/141327954/875c79ff-bc21-4861-af37-82acb3a519e2)
`iperf3 -c 192.168.1.118 -p 5201`
![зображення](https://github.com/bb-qq/r8152/assets/141327954/a0d2e05e-9f98-469e-909e-89c4b82498ed)

**Comment by bb-qq** [comment]
Since simultaneous transfer rates of nearly 2 Gbps are achieved using an Ethernet cable, there appears to be no problem with the WL-NWU330GCA or the driver.

So to address the original issue, it would be a good idea to check the following.

* Whether the WiFi link speed is maintained as expected during file transfer.
* Try connecting the NAS directly to the PC with a cable.
